[package]
name = "lignum_draw"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.12.2"
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.15"

[dev-dependencies]
criterion = "0.5"


[[bench]]
name = "meshing"
harness = false